user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format json_combined escape=json
        '{'
            '"source_ip":"$remote_addr",'
            '"timestamp":"$time_local",'
            '"method":"$request_method",'
            '"path":"$request_uri",'
            '"status":$status,'
            '"response_size":$body_bytes_sent,'
            '"http_referer":"$http_referer",'
            '"user_agent":"$http_user_agent"'
        '}';

    access_log /var/log/nginx/hng-access.log json_combined;

    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
